---
name: Release
"on":
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Package and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Package
        run: scripts/release.sh
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: powersensor-${{github.ref_name}}.zip
          generate_release_notes: true
          fail_on_unmatched_files: true
